# 2_db/build_db.py
# Build the DuckDB database from raw data in 1_data/
# Run: python 2_db/build_db.py  (from project root)
#  or: make db

import duckdb
import pandas as pd
from pathlib import Path

DB_PATH = Path(__file__).parent / "project.duckdb"
DATA_DIR = Path(__file__).parent.parent / "1_data"

# Remove old DB if it exists (clean rebuild)
DB_PATH.unlink(missing_ok=True)

con = duckdb.connect(str(DB_PATH))

# ── Import raw data ─────────────────────────────────────────────
# Example: import a CSV
# df = pd.read_csv(DATA_DIR / "my_data.csv")
# con.sql("CREATE TABLE my_table AS SELECT * FROM df")

# ── Transformations ─────────────────────────────────────────────
# Example: clean, normalize, compute derived columns
# con.sql("""
#     CREATE TABLE clean_data AS
#     SELECT
#         TRIM(name) AS name,
#         LOWER(category) AS category,
#         value::DOUBLE AS value
#     FROM my_table
#     WHERE value IS NOT NULL
# """)

# ── Generate schema.md ──────────────────────────────────────────
schema_lines = ["# Database Schema\n"]
schema_lines.append("_Auto-generated by `build_db.py`. Do not edit manually._\n")
schema_lines.append("_Run `make db` to rebuild the database and regenerate this file._\n")

tables = con.sql("SHOW TABLES").df()
for table_name in tables["name"]:
    cols = con.sql(f"DESCRIBE {table_name}").df()
    n_rows = con.sql(f"SELECT COUNT(*) AS n FROM {table_name}").df()["n"][0]
    schema_lines.append(f"\n## `{table_name}` ({n_rows:,} rows)\n")
    schema_lines.append("| Column | Type | Nullable |")
    schema_lines.append("|--------|------|----------|")
    for _, row in cols.iterrows():
        nullable = "YES" if row.get("null", "YES") == "YES" else "NO"
        schema_lines.append(f"| `{row['column_name']}` | {row['column_type']} | {nullable} |")
    schema_lines.append("")

schema_path = Path(__file__).parent / "schema.md"
schema_path.write_text("\n".join(schema_lines))

con.close()
print(f"✓ Database built: {DB_PATH}")
print(f"✓ Schema written: {schema_path}")
